import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav/Nav";
import AppProvider from "@/redux/provider/AppProvider";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Houzing",
  description: "Generated by create next app",
};
const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={font.className}>
        <AppProvider>
          <Nav/>
          <div>{children}</div>
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
